apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: jaeger
  labels:
    app: jaeger
    jaeger-infra: elasticsearch-service
spec:
  clusterIP: None
  selector:
    app: jaeger-elasticsearch
  ports:
  - port: 9200
    name: elasticsearch
  - port: 9300
    name: transport
